basePath: /api/v1
externalDocs:
  description: ABLECLOUD
  url: https://www.ablecloud.io
info:
  contact:
    email: ycyun@ablecloud.io
    name: APIServer Support
    url: https://www.ablecloud.io/support
  description: This is a Cube-APIServer server.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://ablecloud.io/
  title: Cube APIServer
  version: "1.0"
paths: { }
schemes:
  - http
  - https
securityDefinitions:
  None:
    type: basic
swagger: "2.0"
